name: master
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2.0.0

    # A utility step used to mutate variables with bash
    - name: vars
      id: vars
      env:
        REPO: ${{ github.repository }}
      run: |
        echo "::set-output name=repo-without-owner::$(echo ${REPO} | cut -f 2 -d /)"

    - name: docker
      uses: machine-learning-apps/gpr-docker-publish@v1.4
      id: docker
      with:
        DOCKERFILE_PATH: 'Dockerfile'
        BUILD_CONTEXT: './'
        # Image names are organization/user scoped!
        # Resist the urge to create a 'dev' or 'test' image for a specific repo, for example.
        IMAGE_NAME: ${{ steps.vars.outputs.repo-without-owner }}
        TAG: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
